// Generated by https://quicktype.io

export interface ImageListResponse {
    preview_url:   string;
    sample_url:    string;
    file_url:      string;
    directory:     number;
    hash:          string;
    width:         number;
    height:        number;
    id:            number;
    image:         string;
    change:        number;
    owner:         string;
    parent_id:     number;
    rating:        Rating;
    sample:        boolean;
    sample_height: number;
    sample_width:  number;
    score:         number;
    tags:          string;
    source:        string;
    status:        Status;
    has_notes:     boolean;
    comment_count: number;
}

export enum Rating {
    Explicit = "explicit",
    Questionable = "questionable",
}

export enum Status {
    Active = "active",
}
